# Generated by Django 4.0 on 2022-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employer_first_name_employer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email'),
        ),
    ]
