# Generated by Django 4.0 on 2022-06-23 14:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employer_city_employer_country_employer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
