# Generated by Django 4.0.1 on 2022-05-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_employer_alter_user_is_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='employer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False, verbose_name='freelancer'),
        ),
    ]
