# Generated by Django 4.0.1 on 2022-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_is_employer_alter_user_is_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
