# Generated by Django 4.0 on 2022-06-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='description',
        ),
    ]
