# Generated by Django 4.0 on 2022-05-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
            ],
        ),
    ]
