# Generated by Django 4.0 on 2022-05-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='profile_picture',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
