# Generated by Django 4.0 on 2022-05-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_freelancer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='current_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Job'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='education',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
