# Generated by Django 4.0.5 on 2022-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
