# Generated by Django 4.0.5 on 2022-06-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0002_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
    ]
