# Generated by Django 4.0.4 on 2022-05-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0002_alter_gig_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='User',
            new_name='user',
        ),
    ]
