# Generated by Django 4.0.5 on 2022-06-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_remove_application_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_completed', models.BooleanField(default=False)),
                ('employer_verified', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.application')),
            ],
        ),
    ]
