# Generated by Django 4.0.5 on 2022-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_rename_paid_gig_employer_paid_gig_paid_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='employer_paid',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='paid_freelancer',
        ),
        migrations.AddField(
            model_name='application',
            name='employer_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='paid_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
