# Generated by Django 4.0.4 on 2022-06-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0004_alter_gig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.category'),
        ),
    ]
