# Generated by Django 4.0.5 on 2022-06-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0006_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_date',
            field=models.DateField(default='2022-06-19'),
        ),
        migrations.AddField(
            model_name='gig',
            name='image',
            field=models.ImageField(default='gigs/default.png', upload_to='gigs/'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=255)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gig')),
            ],
        ),
    ]
