# Generated by Django 4.0.5 on 2022-06-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0007_application_applied_date_gig_image_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateField(auto_now=True),
        ),
    ]
