# Generated by Django 4.0.5 on 2022-06-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0009_gig_area_gig_city_gig_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gig',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gig',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
