<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-07-22 10:18
=======
# Generated by Django 4.0.5 on 2022-07-22 09:05
>>>>>>> c65b8678861e15418e0ca1862b926033bcf2449e

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employer')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.freelancer')),
            ],
        ),
    ]
