# Generated by Django 4.0 on 2022-06-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employer'),
        ),
    ]
