# Generated by Django 4.0 on 2022-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0003_alter_message_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=10000000, null=True, verbose_name='Message'),
        ),
    ]
