# Generated by Django 4.0 on 2022-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0004_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='User'),
        ),
    ]
